sudo: required
dist: trusty
language: go
## home folder is /home/travis/gopath/src/github.com/radanalyticsio/radanalyticsio.github.io
services:
- docker
matrix:
  include:
    - env: TO_TEST=pyspark-templates OPENSHIFT_VERSION=v3.10
    - env: TO_TEST=java-templates OPENSHIFT_VERSION=v3.10
    - env: TO_TEST=scala-templates OPENSHIFT_VERSION=v3.10
  fast_finish: true

before_install:
## add insecure-registry and restart docker
- export TEST_DIR=`pwd`
- export ORIGIN_DIR=$TEST_DIR/../origin
- |
      wget https://raw.githubusercontent.com/radanalyticsio/radanalyticsio.github.io/master/resources.yaml -O master_resources.yaml
      diff master_resources.yaml resources.yaml
      if [ "$?" -eq 0 ]; then
          echo "No change in resources.yaml, exiting ..."
          exit 0
      fi
      ./travis-helpers/prepare.sh

install:
- git clone https://github.com/radanalyticsio/oshinko-s2i
- sudo chmod -R a+rwX $TEST_DIR/oshinko-s2i
- cp resources.yaml $TEST_DIR/oshinko-s2i/test/e2e/resources

before_script:
script:
- if [ "$TO_TEST" = "pyspark-templates" ]; then export TEST_ONLY=1; cd oshinko-s2i; S2I_TEST_LOCAL_IMAGES=false test/e2e/run.sh templates/pyspark-py27/radio ; fi
- if [ "$TO_TEST" = "java-templates" ]; then export TEST_ONLY=1; cd oshinko-s2i;    S2I_TEST_LOCAL_IMAGES=false test/e2e/run.sh templates/java/radio ; fi
- if [ "$TO_TEST" = "scala-templates" ]; then export TEST_ONLY=1; cd oshinko-s2i; S2I_TEST_LOCAL_IMAGES=false test/e2e/run.sh templates/scala/radio ; fi
notifications:
 email:
   on_success: never
   on_failure: never
